[build-system]
requires = [
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "wexample-filestate"
version = "0.0.26"
description = "Package that allows you to manage the state of files and directories using YAML configuration files."
authors = [
    { name = "weeger", email = "contact@wexample.com" },
]
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pip-tools",
    "pydantic",
    "pytest",
    "wexample-config==0.0.26",
    "wexample-helpers==0.0.26",
    "wexample-prompt==0.0.25",
]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.license]
text = "MIT"

[project.urls]
homepage = "https://github.com/wexample/python-filestate"

[tool.setuptools.packages.find]
include = [
    "*",
]
